#!/bin/bash -ef

me=$(dirname "$0")
source "$me/inventory.bash"

function deploy() {
    for virtualMachine in ${!virtualMachines[@]}; do
        macAddr=${virtualMachines[$virtualMachine]}
        echo $virtualMachine $macAddr

        if [ -f $virtualMachine.xml ]; then
            echo "VM $virtualMachine exists, skipping"
            continue
        fi

        cat > "user-data-$virtualMachine.yaml" << EOF
#cloud-config

preserve_hostname: false
fqdn: $virtualMachine

users:
  - name: pikachu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHCJXc/MvGBHxpJ12mB1Hy7M6trfWoqPsw1zbGHkN6f0

packages:
  - wget
  - curl
  - bash-completion
  - cloud-initramfs-growroot
  - tcpdump
  - htop

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false  
      
EOF
        cp $imageName $virtualMachine.qcow2
        qemu-img resize $virtualMachine.qcow2 200G

        virt-install \
            --name $virtualMachine \
            --memory 8192 \
            --vcpus 4 \
            --os-variant ubuntu22.04 \
            --disk $virtualMachine.qcow2 \
            --network bridge=br0,model=virtio,mac=$macAddr \
            --nographics \
            --noautoconsole \
            --accelerate \
            --check-cpu \
            --cloud-init user-data=user-data-$virtualMachine.yaml

        virsh autostart $virtualMachine 
        virsh dumpxml $virtualMachine > $virtualMachine.xml
        rm user-data-$virtualMachine.yaml
    done

    virsh list --all
}

deploy
