#!/bin/bash -ef

me=$(dirname "$0")
source "$me/inventory.bash"

function undeploy() {
    for virtualMachine in ${!virtualMachines[@]}; do
        virsh destroy --domain $virtualMachine || true
        virsh undefine $virtualMachine --delete-snapshots --remove-all-storage || true
        rm $virtualMachine.xml $virtualMachine.qcow2
    done
}

undeploy
